@api_Host=https://localhost:7077
@randomId = {{$random.integer(1000, 9999)}}

###
// Create a new party
// @name createParty
POST {{api_Host}}/parties
Content-Type: application/json

{
    "name": "Sample Party {{randomId}}",
    "type": "Birthday",
    "email": "some{{randomId}}@emai.com"
}


###
// Get a party by ID
// @name getPartyById

GET {{api_Host}}/parties/{{createParty.response.body.id}}
Accept: application/json

